# Generated by Django 5.0.3 on 2024-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
