# Generated by Django 5.0.3 on 2024-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_identity',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
